### PR TITLE
Add Spanish (Spain) Translation By Breathingdog

### PR DESCRIPTION
**Pull request by harding**
This adds the Spanish translation by @breathingdog as provided in https://github.com/bitcoin/bitcoin.org/issues/822

I reviewed the whole translation using Google Translate and didn't see anything missing nor any unexpected additions.

### CODE REVIEW

**Comment by saivann** [comment]
@breathingdog @harding Fantastic, thanks!

**Comment by breathingdog** [comment]
@harding @saivann I know this is a technical place, but let me say thanks for your work. I like too much your thoroughly way of working.

**Comment by saivann** [comment]
@breathingdog Well, thanks **you** for your involvement and for going through these steps. It's always super helpful to work with contributors like you ;) .

**Comment by harding** [comment]
@breathingdog yes, thank you!

**Comment by breathingdog** [comment]
@saivann @harding a pleasure!

**Pull request merged**
