### PR TITLE
Swedish translation of the Bitcoin whitepaper

### PR DESCRIPTION
**Pull request by hanspandeya**
"Bitcoin: A Peer-to-Peer Electronic Cash System" has been translated into "Bitcoin: Ett peer-to-peer elektroniskt kontantsystem". I have used Swedish terms that were used in 2008 when the whitepaper was written so the translation is closer to the original and more informative. "Electronic Cash System" used in 2008 evolved into "digitalt betalsystem" (Digital Payment System") and then into "virtuellt valutasystem" ("Virtual Currency System") which is the latest when Bitcoin is discussed nowadays in Sweden. But the terminology will keep evolving and it is therefore convenient to stick to the original words used in 2008.

### CODE REVIEW

**Comment by harding** [comment]
@hanspandeya hey, I'm sorry I haven't had a chance to review this yet.  I just wanted to let you know I haven't forgotten about it.

**Comment by hanspandeya** [comment]
no problem. gave me time to make corrections. I kept spotting mistakes but
now they've all be corrected :)

On Fri, Jul 3, 2015 at 5:37 AM, David A. Harding <notifications@github.com>
wrote:

> @hanspandeya <https://github.com/hanspandeya> hey, I'm sorry I haven't
> had a chance to review this yet. I just wanted to let you know I haven't
> forgotten about it.
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/saivann/bitcoinwhitepaper/pull/5#issuecomment-118222443>
> .
>



-- 
Med vänlig hälsning / Kind regards

Hans Pandeya

**Comment by harding** [comment]
@hanspandeya so sorry it took me so long to review this.  Here's what I did:

The document had a bunch of images that were out of alignment and which were not combined (making them hard to move).  I fixed that here: https://github.com/harding/bitcoinwhitepaper/blob/swedish/bitcoin_se.odt

Could you review the images to make sure I didn't mess anything up?  (Note, I did choose to move one of them down a paragraph to improve the layout.)

I reviewed the above linked document using Google Translate---which isn't perfect---and had just a few questions:

1.  According to Google Translate, section six ends with it saying "fully inflationary" rather than the original "fully inflation free".  Could you check to see if that's an error in your translation or a problem with Google Translate?

2. Google Translate translates the title and some of the text in Section 9 to "sharing" rather than the original "splitting".  Can you check to make sure the Swedish is used correctly there?

3. In English, the possessive form uses an apostrophe followed by an S.  Is it similar in Swedish?  If so, section 4 should say "Adam Back's Hashcash" rather than "Adam Backs Hashcash"

Those are the only possible problems I found.  Let me know if any of them require fixing.

Thanks again!

**Comment by hanspandeya** [comment]
My answers:

The images look fine.

1. I checked, its correct. The two English words, "Inflation free" become
one word, "inflationsfri", when translated into Swedish.

2. Same here, its correct. The Swedish word "delning" means "splitting".
Google Translate is confused because the Swedish word "dela" means both
"share" and "split". However, "delning" means only "splitting".

3. In Swedish, the possesive form uses the letter  "s" but not the
apostrophe. It  looks funny, but it is correct.

On Sun, Jul 19, 2015 at 10:59 PM, David A. Harding <notifications@github.com

**Comment by harding** [comment]
@hanspandeya excellent!  Thanks.  In a moment, I'll merge the version of the document that I checked and then open a pull request to add the PDF version to Bitcoin.org.  Thanks!

**Comment by harding** [comment]
Merged as 53ffdc577e5e3f98b9936e220b521dae8bd03279

**Comment by harding** [comment]
Bitcoin.org pull request: https://github.com/bitcoin-dot-org/bitcoin.org/pull/967

**Comment by saivann** [comment]
@hanspandeya Thanks for your responsiveness after such a long delay. Your work is truly appreciated.

**Comment by hanspandeya** [comment]
I did one more correction and committed it 5 days ago. Could it be merged?

**Comment by harding** [comment]
I see it in your repository.  I'll review and merge it here as soon as I get a chance, then update the PR for Bitcoin.org before merging it there.  Thanks for mentioning it!

**Comment by hanspandeya** [comment]
thnx!

**Comment by harding** [comment]
@hanspandeya I reviewed the updated translation and...

1. Added it here as https://github.com/saivann/bitcoinwhitepaper/commit/7cd29e1af6b78d0010afaace180482cafa801a16

2. Updated the PR with the PDF for the Bitcoin.org website: https://github.com/bitcoin-dot-org/bitcoin.org/pull/967#issuecomment-126536769

Thanks again for your help.

**Pull request closed without merging**
