### PR TITLE
Italian translation

### PR DESCRIPTION
**Pull request by terzim**
First draft of Italian translation by @terzim . Open for review by native speakers.

### CODE REVIEW

**Comment by harding** [comment]
@terzim thanks for submitting this!  I read through a Google Translate version of the document (back into English) to see if I could find any technical errors, and I didn't see any.  I'll ask in the #bitcoin IRC chatroom if there are any Italian speakers who can review the document for grammar.

If anyone is reading this who isn't familiar with GitHub, the direct link to the file (an LibreOffice document) is here: https://github.com/terzim/bitcoinwhitepaper/blob/6c4bce0c1d1f4c0dae6b950240b082ffd04c02c8/bitcoin_it.odt?raw=true

**Comment by terzim** [comment]
thanks @harding for doing the technical check. ... Keep me in the loop. If I wish to edit to improve readability in Italian, do I have to submit a pull request each time or I can edit directly in master branch?

Also thanks for giving the instructions on how to edit images in LibreOffice. Very useful.

**Comment by harding** [comment]
@terzim any changes will need to be submitted here as a pull request so we can review them (although until we merge this pull request, you can make edits and push new commits to your own master branch).

I'm still waiting to see if we can find any other Italian speakers to review this, but if we can't within a reasonable amount of time, we may merge it anyway based on the Google Translate-based check.

If you ever have any questions, please don't hesitate to ask.  I'm happy to help.

**Comment by terzim** [comment]
@harding 
note: Commits on May 3, 2015

    @terzim

    Italian translation …
    terzim authored 2 days ago

Commits on May 5, 2015

    @terzim

    deleting old italian translation.
    terzim authored 5 minutes ago

@terzim

Adding reviewed and corrected Italian translation …
terzim authored 3 minutes ago

**Comment by terzim** [comment]
@pedrosoftz , @simonecarp

**Comment by harding** [comment]
@terzim sorry for the delay responding.  I hope to find time today or tomorrow to review the changes.  Thanks again!

**Comment by terzim** [comment]
thank you. @harding . would be good to get it done this weekend. I certify that the translation is now of good quality (i have to admit first version was a bit raw in terms of readibility).

**Comment by saivann** [comment]
@harding @terzim I should be able to review it today!

**Comment by terzim** [comment]
@saivann thank you very much.

**Comment by saivann** [comment]
(My comments are for commit 8b65169)

@terzim Thank you very much for your work on this. This looks very good to me in general, I haven't found much parts that leaved me with uncertainty. Please see my comments below. Note; you know better than me if I have found valid improvements, please feel free to pick what is right and what isn't.

--

"alla perdita della capacità di effettuare pagamenti non reversibili per i servizi reversibili"

This one seems to say 
"loss of ability to make non-reversible payments for reversible services"

The English string says 
"loss of ability to make non-reversible payments for *non*-reversible services"

(Is there a missing negation here?)

--

"l'incentivo può transizionare interamente"

Is there a typo in "transizionare"?

--

"E' possibile verificare"

Is there a typo in "E'"?

--

Side note:

I wondered for a moment if there was a more direct translation for escrow than "deposito di garanzia" (security deposit, if I understand it correctly). You probably know this better than me. I think otherwise the current term looks just fine.

I also haven't verified if your translation of these specific terms exists in Italian, or if it would be better to use the English term:

"Gambler's Ruin problem"
"Binomial Random Walk"
"Poisson distribution"
"Poisson density"

**Comment by terzim** [comment]
Dear @saivann . thank you for taking the time of this thorough review. 

My comments below. Also, please run a track change function to see little changes. 

"alla perdita della capacità di effettuare pagamenti non reversibili per i servizi reversibili"

This one seems to say
"loss of ability to make non-reversible payments for reversible services"

The English string says
"loss of ability to make non-reversible payments for non-reversible services"

(Is there a missing negation here?)
[MT] you were right. corrected. 

"l'incentivo può transizionare interamente"

Is there a typo in "transizionare"?
[MT] changed "transizionare" with "migrare"

"E' possibile verificare"

Is there a typo in "E'"?
[MT] no typo. I just corrected all accents and apostrophes

Side note:

I wondered for a moment if there was a more direct translation for escrow than "deposito di garanzia" (security deposit, if I understand it correctly). You probably know this better than me. I think otherwise the current term looks just fine.

[MT] "Deposito di garanzia" can stay. An alternative translation is "acconto di garanzia" but it just does not sound good. 

I also haven't verified if your translation of these specific terms exists in Italian, or if it would be better to use the English term:

"Gambler's Ruin problem"
"Binomial Random Walk"
"Poisson distribution"
"Poisson density"

[MT] for "Gambler's Ruin problem" the Italian translation is "problema della rovina del giocatore". In any case, I left the English term in brackets

"Binomial random walk" is translated as "passeggiata aleatoria binomiale". In any case, I left the English term in brackets. 

"Poisson distribution" and "Poisson density" are used in the current Italian math language so no need to complement with the English term

**Comment by harding** [comment]
@terzim thanks!  Later today, I'll make a quick final review and create a pull request suggesting we add this to Bitcoin.org.

**Comment by saivann** [comment]
@terzim Many thanks again! My comments for commit d9b131b :

I've reviewed the changes and this all looks good to me, except a possible typo in a word added in that commit:

"di densità di proabilità Poisson"

I guess proabilità should be probabilità?

@harding Thanks for your help and for yourself to check and merge the final document! Do you think it would be relevant to move the content of this repository into files/bitcoinpaper on the main repository?

**Comment by terzim** [comment]
yes. probabilità !

Strange that the spellcheck did not pick this up.

On 09/05/2015 17:35, saivann wrote:
>
> @terzim <https://github.com/terzim> Many thanks again! My comments for
> commit d9b131b
> <https://github.com/saivann/bitcoinwhitepaper/commit/d9b131b3d9caba121260f699e4c4102dc160c5c5>
> :
>
> I've reviewed the changes and this all looks good to me, except a
> possible typo in a word added in that commit:
>
> "di densità di proabilità Poisson"
>
> I guess proabilità should be probabilità?
>
> @harding <https://github.com/harding> Thanks for your help and for
> yourself to check and merge the final document! Do you think it would
> be relevant to move the content of this repository into
> files/bitcoinpaper on the main repository?
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/saivann/bitcoinwhitepaper/pull/4#issuecomment-100514673>.
>


-- 
Kind Regards / Distinti Saluti,

Massimiliano
+44 758 631 21 91

**Comment by terzim** [comment]
@saivann @harding would you like me to correct this word "probabilita'" and push another file or you can amend the mistakr yourselves?

**Comment by harding** [comment]
@terzim yes, could you please update it?  Thanks!

**Comment by terzim** [comment]
@saivann @harding done, sorry about that.

**Comment by saivann** [comment]
Commenting on commit 544b4ef

"FLe firme digitali offrono una soluzione parziale al problema"

"Le" has been replaced by "FLe" (with two uppercase character). My impression is this is likely a typo, is it?

@terzim Updating the document is always appreciated if you have time. But if it's not possible, just let me know and I can update the document on my side. Thanks

**Comment by terzim** [comment]
@saivann this is not an issue. I would like to have a perfect result. But I don't understand why this is happening :) Maybe fat fingers? :) Because the FLe was not there before...

Anyway, thanks for pointing it out. I re-uploaded the file.

**Comment by saivann** [comment]
@terzim Commit 326aa2a looks good to me, thanks! That indeed looked like an accidental extra letter :) .

@harding Just let me know if you want to make additional review before I merge the document. As far as I'm concerned, I am all for generating the final PDF and open the pull request for inclusion on bitcoin.org.

**Comment by harding** [comment]
Reviewing this now.  I'll merge as soon as I finish, and immediately after that I'll prepare the PR for Bitcoin.org.  Thanks!

**Pull request closed without merging**
